### ISSUE TITLE
New python package dependency 

### ISSUE THREAD

**Issue by Kennyl** [Technosoft2000/docker-calibre-web#1]
Following package is not included in latest git source requirement.txt.

gevent  (may need libevent)
google-api-python-client 
pydrive

and suggest static app.db by
ln -s /books/app.db $APP_HOME/app/app.db

**Comment by Technosoft2000** [comment]
Thanks for the hint, I'll include https://github.com/janeczku/calibre-web/blob/master/optional-requirements.txt
`gevent==1.2.1
google-api-python-client==1.6.1
greenlet==0.4.12
httplib2==0.9.2
lxml==3.7.2
oauth2client==4.0.0
pyasn1-modules==0.0.8
pyasn1==0.1.9
PyDrive==1.3.1
PyYAML==3.12
rsa==3.4.2
six==1.10.0
uritemplate==3.0.0`

I like your idea with the static __app.db__, so I'll add this change too.

**Comment by Technosoft2000** [comment]
New version v1.1.0 is available on Docker Hub https://hub.docker.com/r/technosoft2000/calibre-web/builds/bzmflfhbqerktwz5gah7u3g/

**Comment by Kennyl** [comment]
Hi,

I missed suggestion on the link of new gdrive integration.

ln -s /books/gdrive.db "$APP_HOME/app/gdrive.db"

**Comment by Technosoft2000** [comment]
New version v1.1.1 is available on Docker Hub https://hub.docker.com/r/technosoft2000/calibre-web/builds/bpgnn7sae5psfowvdscpsaa/

**Comment by Kennyl** [comment]
Thx for your update.
