### ISSUE TITLE
Is it possible to customize the location of the books directory?

### ISSUE THREAD

**Issue by samyak-jain** [Technosoft2000/docker-calibre-web#107]
I can see that we have create a books volume here: https://github.com/Technosoft2000/docker-calibre-web/blob/6ecbdb78aad268f6270667817e399e3daf2c7cd1/Dockerfile#L301

This is unlike the other volumes where they are customizable using APP_HOME. Is there anything preventing us from using /custom-directory/books for storing the books?

**Comment by Technosoft2000** [comment]
Hi @samyak-jain,

you control your `/books` volume with the volume option `-v <your Calibre books folder>:/books \` while container creation. So I don't see any need to control it over an additional environment variable. What's your use case that you need it as environment variable?

`<your Calibre books folder>` is the directory on your host or your docker volume which you want to map as `/books` inside the container.
