### ISSUE TITLE
Setting Log Level?

### ISSUE THREAD

**Issue by snesbittsea** [Technosoft2000/docker-calibre-web#11]
Is there an environment variable or other means to set the server Log Level? It appears to be set at INFO which is a bit noisy.

Thx,

-steve

**Comment by Technosoft2000** [comment]
> Is there an environment variable or other means to set the server Log Level?
No such variable doesn't exist.

The Calibre Web Application starts the gevent WSGI server without passing an own logging handler which can be controlled and so the WSGI server uses his default logger. See als at 
https://github.com/janeczku/calibre-web/blob/master/cps/web.py at line 3031:
`gevent_server = WSGIServer(('', ub.config.config_port), app)`

In my opinion Calibre Web should support the possibility to set the logging level on the web interface - so I suggest to open an enhancement ticket at https://github.com/janeczku/calibre-web/issues

**Comment by snesbittsea** [comment]
Done. See https://github.com/janeczku/calibre-web/issues/310
