### ISSUE TITLE
Failed to create path /books/Library/Unknown/Smart-Contract Value-Transfer Protocols (Permission denied).

### ISSUE THREAD

**Issue by hysci** [Technosoft2000/docker-calibre-web#14]
I used docker-compose to start it. 
version: '2'
services:
  calibre-web:
    image: Technosoft2000/docker-calibre-web
    ports:
      - '8083:8083'
    volumes:
      - /opt/opds/data:/books
      - /opt/opds/web:/calibre-web
Then execute: sudo docker-compose up
When an admin user upload a pdf file, the error message was as follows:
Failed to create path /books/Library/Unknown/Smart-Contract Value-Transfer Protocols (Permission denied).
Note: selinux is not the reason why this happens, because the following commands were executed:
sudo chcon -Rt svirt_sandbox_file_t /opt/opds/data
sudo chcon -Rt svirt_sandbox_file_t /opt/opds/web

**Comment by Technosoft2000** [comment]
Hi @hysci,

could you please provide the log from the container startup - my assumption is that the container user & group doesn't have the right to write at the directory _/books_ 
You should try to pass & use the PGID and PUID environment setting.

**Comment by hysci** [comment]
I got it. It should be not a bug because the PGID and PUID does not match, thanks for your reminding. This bug could be closed.
