### ISSUE TITLE
Language and cover image url cannot be saved in metadata?

### ISSUE THREAD

**Issue by xmeng1** [Technosoft2000/docker-calibre-web#19]
Language and cover image URL cannot be saved in metadata?

I use the docker to run the server, and I found I cannot add Language to the book in edit metadata. So How can I get some logs to debug this issue?

**Comment by Technosoft2000** [comment]
Hi @xmeng1 

to monitor the logs of the container in realtime: `docker logs -f calibre-web`

to monitor the logs of Calibre Web: `docker exec -it calibre-web tail -f /calibre-web/app/calibre-web.log`

At the 'Admin' page you have to set the logging level for /books from **INFO** to **DEBUG** and afterwards you've to restart the container to get more detailed information at _calibre-web.log_ 

Adding and removing a Language to a book works here, but adding a cover image URL doesn't work and I can't see any error at the log file. So for me it looks like an issue of the application itself and not of the docker container; I'll try to install the application directly on a Linux VM and check how it behaves there.

**Comment by xmeng1** [comment]
thanks, I will check the log. I found that when adding book and input the language, it works. but when edit and add the language, the value is not persisted.

**Comment by Technosoft2000** [comment]
Sorry for late testing - I've tested now on a Ubuntu 16.04 Virtual Machine directly installed without container and the Calibre-Web application has there the same issue, so it has nothing to do with the container. In addition I can't see anything at the calibre-web.log file, but I've created now an issue at Calibre-Web as you can see ;)
