### ISSUE TITLE
 Error when i start the container and map my volume [saitoh183]

### ISSUE THREAD

**Issue by Technosoft2000** [Technosoft2000/docker-calibre-web#2]
Error from a comment from https://hub.docker.com/r/technosoft2000/calibre-web/ by user saitoh183:

gives the error below when i start the container and map my volume.

```
[INFO] Docker image version: 1.1.2
[INFO] Create group calibre with id 15000
[INFO] Create user calibre with id 15000
[INFO] Current active timezone is EDT
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre
[INFO] Current git version is:
git version 2.13.0
[INFO] Checkout the latest Calibre-Web version ...
[INFO] ... git clone -b master --single-branch https://github.com/janeczku/calibre-web.git /calibre-web/app -v
Cloning into '/calibre-web/app'...
POST git-upload-pack (189 bytes)
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...
[INFO] ... current git status is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
e6c6c26fd1ec363c3065f03c388a5d628ed6331e
[INFO] ... pulling sources
Already up-to-date.
[INFO] ... git status after update is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
e6c6c26fd1ec363c3065f03c388a5d628ed6331e
[INFO] Launching Calibre-Web ...
Traceback (most recent call last):
File "/calibre-web/app/cps.py", line 13, in <module>
from cps import web
File "/calibre-web/app/cps/web.py", line 18, in <module>
import ub
File "/calibre-web/app/cps/ub.py", line 525, in <module>
Base.metadata.create_all(engine)
File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3918, in create_all
tables=tables)
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1928, in _run_visitor
with self._optional_conn_ctx_manager(connection) as conn:
File "/usr/lib/python2.7/contextlib.py", line 17, in enter
return self.gen.next()
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1921, in _optional_conn_ctx_manager
with self.contextual_connect() as conn:
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2112, in contextual_connect
self._wrap_pool_connect(self.pool.connect, None),
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2151, in _wrap_pool_connect
e, dialect, self)
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1465, in _handle_dbapi_exception_noconnection
exc_info
File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
return fn()
File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 387, in connect
return _ConnectionFairy._checkout(self)
File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 766, in _checkout
fairy = _ConnectionRecord.checkout(pool)
File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 516, in checkout
rec = pool._do_get()
File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1229, in _do_get
return self._create_connection()
File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
return _ConnectionRecord(self)
File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 461, in init
self.connect(first_connect_check=True)
File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 651, in connect
connection = pool._invoke_creator(self)
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
return dialect.connect(cargs, **cparams)
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 393, in connect
return self.dbapi.connect(cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
```

**Comment by saitoh183** [comment]
i also tried to use the PGID/PUID and got another type of error
`     ~~~~~         Calibre Web       ~~~~~

[INFO] Docker image version: 1.1.2
[INFO] Create group calibre with id 100
addgroup: gid '100' in use
[INFO] Create user calibre with id 1000
adduser: unknown group calibre
[INFO] Current active timezone is EDT
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre
chown: unknown user/group calibre:calibre
[INFO] Current git version is:
git version 2.13.0
[INFO] Checkout the latest Calibre-Web version ...
[INFO] ... git clone -b master --single-branch https://github.com/janeczku/calibre-web.git /calibre-web/app -v
error: failed switching to "calibre:calibre": unable to find user calibre: no matching entries in passwd file
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...
[INFO] ... current git status is
error: failed switching to "calibre:calibre": unable to find user calibre: no matching entries in passwd file
[INFO] ... pulling sources
error: failed switching to "calibre:calibre": unable to find user calibre: no matching entries in passwd file
[INFO] ... git status after update is
error: failed switching to "calibre:calibre": unable to find user calibre: no matching entries in passwd file
ln: /calibre-web/app/vendor/kindlegen: No such file or directory
[INFO] Launching Calibre-Web ...
error: failed switching to "calibre:calibre": unable to find user calibre: no matching entries in passwd file`


Here is the container details:
`[
    {
        "Id": "f340a2e5da06f64cbc18954cb12f0879231a6d9dd128c0279fab5e3e4653787c",
        "Created": "2017-05-29T15:18:49.013046435Z",
        "Path": "/bin/bash",
        "Args": [
            "-c",
            "/init/start.sh"
        ],
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2017-05-29T15:19:49.348206282Z",
            "FinishedAt": "2017-05-29T15:19:49.465863533Z"
        },
        "Image": "sha256:af07310c9173fba71a19c2afe209bdd8ce1caedea1609af2a643b33a491c11f5",
        "ResolvConfPath": "/var/lib/docker/openmediavault/containers/f340a2e5da06f64cbc18954cb12f0879231a6d9dd128c0279fab5e3e4653787c/resolv.conf",
        "HostnamePath": "/var/lib/docker/openmediavault/containers/f340a2e5da06f64cbc18954cb12f0879231a6d9dd128c0279fab5e3e4653787c/hostname",
        "HostsPath": "/var/lib/docker/openmediavault/containers/f340a2e5da06f64cbc18954cb12f0879231a6d9dd128c0279fab5e3e4653787c/hosts",
        "LogPath": "/var/lib/docker/openmediavault/containers/f340a2e5da06f64cbc18954cb12f0879231a6d9dd128c0279fab5e3e4653787c/f340a2e5da06f64cbc18954cb12f0879231a6d9dd128c0279fab5e3e4653787c-json.log",
        "Name": "/calibre-web",
        "RestartCount": 10,
        "Driver": "overlay2",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/etc/localtime:/etc/localtime:ro",
                "/media/audiobooks/Calibre_books:/books:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "8083/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8088"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/openmediavault/overlay2/8b66254402f72158ff494015964951e0b1c89774ca73b5b13835fde20d11d9d5-init/diff:/var/lib/docker/openmediavault/overlay2/4fb4606060ff4c5ad6ea5091b896bcd56489e906fb8b123cf69704264b167fd0/diff:/var/lib/docker/openmediavault/overlay2/913f47f9aedd3f1efeb17a8f58c4be85dd81af1babeadc9b0ab8664800e3028d/diff:/var/lib/docker/openmediavault/overlay2/3d36a408abcd207f8f789cd60326eafc647440e5b9f0d0673a3d54a516bb4a1b/diff:/var/lib/docker/openmediavault/overlay2/ded68b7236c808585f0df28527e038374eb9ef965ea86ac49db97e9252ba13b6/diff:/var/lib/docker/openmediavault/overlay2/f6d45f5881875187c6cb79b062a804a2f0620864ba26dc2e502ed090000dbf61/diff:/var/lib/docker/openmediavault/overlay2/1ed7bf9cdcd8aa93f18e6f98955ca63664864e853c569fbbc3d31d2145382b98/diff:/var/lib/docker/openmediavault/overlay2/bc3d2354a426771b7d8c97e54efe0ff5bc25bb5e5e74387dcb072e95bad7a603/diff:/var/lib/docker/openmediavault/overlay2/341e62c80cb90681a3035d1db6cd088e18abea3bc4bea0aca533567fa1b06e57/diff",
                "MergedDir": "/var/lib/docker/openmediavault/overlay2/8b66254402f72158ff494015964951e0b1c89774ca73b5b13835fde20d11d9d5/merged",
                "UpperDir": "/var/lib/docker/openmediavault/overlay2/8b66254402f72158ff494015964951e0b1c89774ca73b5b13835fde20d11d9d5/diff",
                "WorkDir": "/var/lib/docker/openmediavault/overlay2/8b66254402f72158ff494015964951e0b1c89774ca73b5b13835fde20d11d9d5/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/media/audiobooks/Calibre_books",
                "Destination": "/books",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "srv-saitoh",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8083/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "VERSION=1.1.2",
                "TERM=xterm",
                "LANG=en_EN.UTF-8",
                "LANGUAGE=en_EN:en",
                "LC_ALL=en_EN.UTF-8",
                "SET_CONTAINER_TIMEZONE=false",
                "CONTAINER_TIMEZONE=UTC",
                "GOSU_VERSION=1.10",
                "PKG_BASE=bash tzdata git",
                "PUSER=calibre",
                "PGROUP=calibre",
                "APP_NAME=Calibre-Web",
                "APP_HOME=/calibre-web",
                "APP_REPO=https://github.com/janeczku/calibre-web.git",
                "APP_BRANCH=master",
                "AMAZON_KG_TAR=kindlegen_linux_2.6_i386_v2_9.tar.gz",
                "AMAZON_KG_URL=http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz",
                "CALIBRE_PATH=/books",
                "PKG_DEV=make gcc g++ python-dev openssl-dev libffi-dev libxml2-dev libxslt-dev",
                "PKG_PYTHON=ca-certificates py-pip python py-libxml2 py-libxslt py-lxml libev",
                "PKG_IMAGES=imagemagick imagemagick-doc imagemagick-dev",
                "MAGICK_HOME=/usr",
                "PGID=100",
                "PUID=1000"
            ],
            "Cmd": [
                "/bin/bash",
                "-c",
                "/init/start.sh"
            ],
            "ArgsEscaped": true,
            "Image": "technosoft2000/calibre-web:latest",
            "Volumes": {
                "/books": {}
            },
            "WorkingDir": "/calibre-web/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "image.base.date": "2017-05-25",
                "image.base.description": "Docker image for Alpine based docker images by Technosoft2000",
                "image.base.version": "3.6-1",
                "image.date": "2017-05-28",
                "image.description": "Docker image for Calibre Web, based on docker image of Alpine",
                "image.version": "1.1.2",
                "url.base.docker": "https://hub.docker.com/r/technosoft2000/alpine-base",
                "url.base.github": "https://github.com/Technosoft2000/docker-alpine-base",
                "url.base.support": "https://cytec.us/forum",
                "url.docker": "https://hub.docker.com/r/technosoft2000/calibre-web",
                "url.github": "https://github.com/Technosoft2000/docker-calibre-web",
                "url.support": "https://cytec.us/forum"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "def6f90962e26859243b214f5a234208937ec870d019d19f7a39aeb376de40a1",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/def6f90962e2",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "eab989b345284ab2f6d60e449554c27dcc948e56fdfe2f750b47069e8caf46d2",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]`

Also im using openmediavault with the docker plugin if that is important

**Comment by saitoh183** [comment]
@Technosoft2000  any update?

**Comment by Technosoft2000** [comment]
@saitoh183 
sorry had no time before to check this, but now I do it ;)

The problem with your specified PGID is that this value is already in use by default by the Alpine Linux system - here is the extract of _/etc/group_ :
```
root:x:0:root
bin:x:1:root,bin,daemon
daemon:x:2:root,bin,daemon
sys:x:3:root,bin,adm
adm:x:4:root,adm,daemon
tty:x:5:
disk:x:6:root,adm
lp:x:7:lp
mem:x:8:
kmem:x:9:
wheel:x:10:root
floppy:x:11:root
mail:x:12:mail
news:x:13:news
uucp:x:14:uucp
man:x:15:man
cron:x:16:cron
console:x:17:
audio:x:18:
cdrom:x:19:
dialout:x:20:root
ftp:x:21:
sshd:x:22:
input:x:23:
at:x:25:at
tape:x:26:root
video:x:27:root
netdev:x:28:
readproc:x:30:
squid:x:31:squid
xfs:x:33:xfs
kvm:x:34:kvm
games:x:35:
shadow:x:42:
postgres:x:70:
cdrw:x:80:
usb:x:85:
vpopmail:x:89:
users:x:100:games
ntp:x:123:
nofiles:x:200:
smmsp:x:209:smmsp
locate:x:245:
abuild:x:300:
utmp:x:406:
ping:x:999:
nogroup:x:65533:
nobody:x:65534:
/etc/group
```
so the PGID should be >= 1000 to don't get in conflict with groups which already exists.
Nevertheless I'll try now to fix the issue with the default PGID an PUID.

**Comment by saitoh183** [comment]
@Technosoft2000 

I used PUID 1000 and PGID 100 since the host has that account and group assigned to the folder where the metadata.db is. So If I put something else or nothing, will it be able to get to the folder on the host that I mapped to a docker volume? 

_Sent from my Samsung SM-G950W using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Technosoft2000** [comment]
@saitoh183 

At the current image I can't support PGID 100 because it is already in use and it is not possible to create a second group with PGID 100 inside the docker image. So you would need a group on your host with **PGID >= 1000** so that the mapping will works.

At the moment I work on a new image version to support also PGID < 1000 like your PGID 100, but it seems not so easy to do.

Yesterday I've fixed the issue with the default PGID and PUID at the image but if they are used then the mapped volume `/books` must have read-write-execute permission for others , otherwise the configuration of Calibre-Web can't be finished :-|

I try to fix the PGID issue in the next days and then I'll create a new release version

**Comment by Technosoft2000** [comment]
@saitoh183 
a new version is online v1.1.3 which fixes the problem with PGID
 
get it via `docker pull technosoft2000/calibre-web:v1.1.3` 
or `docker pull technosoft2000/calibre-web:latest`

I support now __PGID < 1000__ and I've tested it with the following creation command:

```
docker create --name=calibre-web --restart=always \
-v /volume1/books/calibre:/books \
-e SET_CONTAINER_TIMEZONE=true \
-e CONTAINER_TIMEZONE=Europe/Vienna \
-e PUID=1000 \
-e PGID=100 \
-p 8082:8083 \
technosoft2000/calibre-web
```

**Comment by saitoh183** [comment]
@Technosoft2000 will check it out

_Sent from my Samsung SM-G950W using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ErroneousBosch** [comment]
I am having this exact same problem, both my puid and pgid are set to 1000 (to match host system)

**Comment by clx81** [comment]
Hello,
I have installation problems on my Synology NAS.
User & Group 'docker' has been created with R/W rights on the newly created folder and sub-folder  '/books' and '/books/calibre'
PGID docker = 65537 - PUID = 1031
after running the following command: 
_docker create --name=calibre-web --restart=always -v /volume1/books/calibre:/books -e SET_CONTAINER_TIMEZONE=true -e CONTAINER_TIMEZONE=Europe/Brussels -e PGID=65537 -e PUID=1031 -p 50000:8083 technosoft2000/calibre-web_

the container is created but stop after starting due to R/W rights on /books folders

Log file is in attach.

I have retried the installation many times but without success.

Your help will be appréciated. Thank you.

Christian
[error.txt](https://github.com/Technosoft2000/docker-calibre-web/files/1203396/error.txt)

**Comment by Technosoft2000** [comment]
Hi Christian,

you should use in your case **PGID=100** ('users' group of Synology) while creation of the container, because at your log I see that the docker group **PGID=65537** has no write access to the mapped _/books_ directory.
So create your container with the following comand:
```
docker create --name=calibre-web --restart=always -v /volume1/books/calibre:/books -e SET_CONTAINER_TIMEZONE=true -e CONTAINER_TIMEZONE=Europe/Brussels -e PGID=100 -e PUID=1031 -p 50000:8083 technosoft2000/calibre-web
```
With this command the container should start successfully.

I'll try to update the Synology NAS section at the README.md as soon as possible so that other users won't get into the same pitfall ;)

**Comment by clx81** [comment]
Hello,

Thank you for your answer. But it's not working. I received now the
following logs.

[INFO] Docker image version: 1.1.6
[INFO] Alpine Linux version: 3.6.0
[WARNING] A group with id 100 exists already [in use by calibre] and will
be modified.
[WARNING] The group calibre will be renamed to calibre
[WARNING] A user with id 1031 exists already [in use by calibre] and will
be modified.
[WARNING] The user calibre will renamed to calibre and assigned to group
calibre
[INFO] Current active timezone is CEST
Mon Aug  7 11:56:52 CEST 2017
[INFO] Container timezone is changed to: Europe/Brussels
[INFO] Change the ownership of /calibre-web (including subfolders) to
calibre:calibre
[INFO] Current git version is:
git version 2.13.0
[INFO] Checkout the latest Calibre-Web version ...
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web
...
[INFO] ... current git status is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
fe52de6b4b730f5b15e430dc34c367b0aafd6ecb
[INFO] ... pulling sources
Already up-to-date.
[INFO] ... git status after update is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
fe52de6b4b730f5b15e430dc34c367b0aafd6ecb
[INFO] kindlegen (Amazon Kindle Generator) will be linked into
/calibre-web/app/vendor
> kindlegen link /calibre-web/app/vendor/kindlegen exists already and won't
be recreated
[INFO] Checking permissions of /books
> Output is: 770 calibre 100 UNKNOWN 1024
> Permissions: 770
> Assigned group: calibre
> Assigned group ID: 100
> Assigned owner: UNKNOWN
> Assigned owner ID: 1024
> Using permissions for checks: 0770
> Check if the group calibre has write access at /books
> The group calibre has write access at /books
[INFO] app.db and gdrive.db will be linked into /books
> create app.db link /calibre-web/app/app.db assigned to source
/books/app.db
> create gdrive.db link /calibre-web/app/gdrive.db assigned to source
/books/gdrive.db
[ERROR] The mapped volume for /books doesn't contain a Calibre database
file 'metadata.db'
> Please fix the volume mapping before you retry to start the container
again
> Stopping the container with errorlevel 1


The volume /books/calibre mapping seems to be correct.

May be, it's simple to solve but I'm new in Docker technologies.

Have a nice day !

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-08-07 9:57 GMT+02:00 Technosoft2000 <notifications@github.com>:

**Comment by Technosoft2000** [comment]
Hi,

so the problem with the rights are solved now as I can see.

The issue is that your _/volume1/books/calibre_ doesn't contain any _metadata.db_ file created via the original Calibre software => https://calibre-ebook.com/ - this is a pre-requirement to successfully run the Calibre-Web application from https://github.com/janeczku/calibre-web
This docker container only provides the environment to successfully run then the Calibre-Web application.

So download Calibre on your PC or Mac and create a new library so that you get a new _metadata.db_ which you can transfer to your directoy _/volume1/books/calibre_ .

In a future release I'll include an initial _metadata.db_ file which will be copied to the target volume if no one exists.

**Comment by clx81** [comment]
Thank you very much for your help !

It's working well now.

2017-08-07 13:42 GMT+02:00 Technosoft2000 <notifications@github.com>:
