### ISSUE TITLE
Empty reply from server on container restart

### ISSUE THREAD

**Issue by mrdziuban** [Technosoft2000/docker-calibre-web#20]
I've found that when stopping and restarting the container, the server does not seem to start up properly and I get `Empty reply from server` when trying to curl the root URL.

I'm running the container with the following command:

```bash
docker run -d --name=calibre-web --restart=always \
  -v /media/books/calibre:/books \
  -v /etc/localtime:/etc/localtime:ro \
  -v /media/books/config:/calibre-web/config \
  -e PGID=1000 -e PUID=1000 -e USE_CONFIG_DIR=true \
  -p 8083:8083 \
  technosoft2000/calibre-web
```

This seems to be related to the `app.db` and `gdrive.db` files. If they already exist in `/calibre-web/config`, I get this error. If I move the files then start the container, it works properly but I need to configure everything again.

Any thoughts? Thanks in advance.

**Comment by Technosoft2000** [comment]
Hi @mrdziuban 

I'm sorry but I can't reproduce the issue here. When I restart the container then it works without any problems and the Calibre Web application is reachable.

Could you please attach the log when you start the container the first time and then in addition the log after restart of the container.

In addition it would be great if you can give me the info which Linux Distrubution and which version of Docker you use. `docker version` then post the output - example:
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Fri Dec 15 19:37:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Fri Dec 15 19:37:44 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by mrdziuban** [comment]
I can reproduce it on Ubuntu 16.04. It seems to happen if I follow these steps:

1. Run the container
2. Go to `/config` and submit the form with a valid calibre library path
3. Stop and remove the container
4. Run a new container with the same settings

Here's a gist with the startup logs:

https://gist.github.com/mrdziuban/9604f998c34ce542688a0df2f3601975

And here's the docker version info:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by Technosoft2000** [comment]
1. Install VM
VirtualBox Image from osboxes.org Ubuntu 16.04.3 Xenial - https://www.osboxes.org/ubuntu/

2. Check user id:
```
osboxes@osboxes:~$ id
uid=1000(osboxes) gid=1000(osboxes) groups=1000(osboxes),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),113(lpadmin),128(sambashare)
```

3. Install docker:
https://docs.docker.com/install/linux/docker-ce/ubuntu/

4. Check docker version:
```
osboxes@osboxes:~$ sudo docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

5. Create calibre and config directory
```
sudo mkdir -p /media/books/calibre
sudo mkdir -p /media/books/config
sudo chown -R osboxes:osboxes /media/books
```

6. Create docker container
```
sudo docker run -d --name=calibre-web --restart=always \
  -v /media/books/calibre:/books \
  -v /etc/localtime:/etc/localtime:ro \
  -v /media/books/config:/calibre-web/config \
  -e PGID=1000 -e PUID=1000 -e USE_CONFIG_DIR=true \
  -p 8083:8083 \
  technosoft2000/calibre-web

[sudo] password for osboxes: 
Unable to find image 'technosoft2000/calibre-web:latest' locally
latest: Pulling from technosoft2000/calibre-web
b56ae66c2937: Pull complete 
49da74a8535b: Pull complete 
46b572006518: Pull complete 
4b460cc5e281: Pull complete 
02eefe89a3e3: Pull complete 
86e9d6cf7a16: Pull complete 
caafac53cbe0: Pull complete 
bf1cd7179a18: Pull complete 
b1461e1bb2f9: Pull complete 
Digest: sha256:96620bffa0235df54e609ee8973cbc37dd2d598cd14d44be20b1b30de9d41b67
Status: Downloaded newer image for technosoft2000/calibre-web:latest
a98f4604fb8e1704126d904b629736c0cd22c5ab9430be37899b4f4d3fdf2513
```

7. Check if it runs and reachable

```
sudo docker ps

CONTAINER ID        IMAGE                        COMMAND                  CREATED              STATUS              PORTS                    NAMES
a98f4604fb8e        technosoft2000/calibre-web   "/bin/bash -c /init/…"   About a minute ago   Up About a minute   0.0.0.0:8083->8083/tcp   calibre-web

```
  At browser: http://localhost:8083

  Then I've done the configuration and loggedin via user: admin and pwd: admin123

8. Check the directory structure and files

```
osboxes@osboxes:/media/books$ tree
.
├── calibre
│   ├── metadata.db
│   └── metadata_db_prefs_backup.json
└── config
    ├── app.db
    └── gdrive.db

2 directories, 4 files	
```
	
  Looks okay :)

9. Stop and remove the container

```

sudo docker stop calibre-web
sudo docker rm calibre-web
sudo docker ps -a

CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

  No container exists anymore

10. Check the directory structure and files after deletion

```
osboxes@osboxes:/media/books$ tree
.
├── calibre
│   ├── metadata.db
│   └── metadata_db_prefs_backup.json
└── config
    ├── app.db
    └── gdrive.db

2 directories, 4 files
```

  Still okay :)

11. Create the docker container again

```
sudo docker run -d --name=calibre-web --restart=always \
  -v /media/books/calibre:/books \
  -v /etc/localtime:/etc/localtime:ro \
  -v /media/books/config:/calibre-web/config \
  -e PGID=1000 -e PUID=1000 -e USE_CONFIG_DIR=true \
  -p 8083:8083 \
  technosoft2000/calibre-web
```

12. Check if it runs and reachable
  
```
sudo docker ps -a

CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                    NAMES
36eca6a3c1da        technosoft2000/calibre-web   "/bin/bash -c /init/…"   10 seconds ago      Up 9 seconds        0.0.0.0:8083->8083/tcp   calibre-web
```

  At browser: http://localhost:8083

  No issue at all, I get the site and it works like a charme


13. Linux info

```
uname -a
Linux osboxes 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

So I'm sorry I really can't reproduce this issue :-|

**Comment by mrdziuban** [comment]
So I dug into this a little more and it seems to happen when using a port other than 8083. I'm actually mapping port 8084 to 8083 in the Docker container like so:

```
sudo docker run -d --name=calibre-web --restart=always \
  -v /media/books/calibre:/books \
  -v /etc/localtime:/etc/localtime:ro \
  -v /media/books/config:/calibre-web/config \
  -e PGID=1000 -e PUID=1000 -e USE_CONFIG_DIR=true \
  -p 8084:8083 \
  technosoft2000/calibre-web
```

Then when setting the initial configuration, I update the default port to 8084. Can you reproduce it using a port other than 8083?

P.S. Sorry my initial description didn't mention that I wasn't using 8083 -- I was trying to put together a minimal example but clearly it's important here.

**Comment by Technosoft2000** [comment]
I've tested now different ports like 8084, 18084 and so on and have no difference on the behavior nor an issues at all.

Could you please check your _calibre-web.log_ if it contains any error - you can copy the log file crom your container to your host with the following command:

`sudo docker cp calibre-web:/calibre-web/app/calibre-web.log /media/books/config/.`

My _calibre-web.log_ has only this entries:
```
[2018-02-06 15:57:38,956] {/calibre-web/app/cps/web.py:230} INFO - Starting Calibre Web...
[2018-02-06 15:57:39,120] {/calibre-web/app/cps.py:28} INFO - Attempting to start gevent
```

I hope that your one contains an error to get a hint why it doesn't work.

**Comment by Technosoft2000** [comment]
This issue is not reproducible and therefore it will be closed .
