### ISSUE TITLE
Raspberry pi 3 version of dockerfile

### ISSUE THREAD

**Issue by Javrd** [Technosoft2000/docker-calibre-web#21]
It could be great to have an arm version of this container in order to run this server on raspberry pi, and it is easy to do that. I have done that cloning your [docker-alpine-base](https://github.com/Technosoft2000/docker-alpine-base) and changing the FROM line in order to get the [arm32 alpine version](https://hub.docker.com/r/arm32v6/alpine/). Once I built the alpine version, I change the docker-calibre-web's dockerfile in order to use the new image. 

It worked fine, except for Kindlegen tool, that unfortunately has no arm version, but that is not related with docker.

I could up a pull request in both repositories ─ if you want ─ with the new dockerfiles. It could be tagged with arm-{version of alpine} for instance.

**Comment by Technosoft2000** [comment]
Hi @Javrd 

thanks for your input. Interesting to see that anyone wants the image for Raspberry Pi 3 :)
So I'll include in the next days a first version of an **arm32v6** build with your suggested changes and configure the _hub.docker.com_ repo.

**Comment by paulhybryant** [comment]
Hello @Technosoft2000 

I am also looking for a docker image that runs on arm64v8.
Do you think such an image can be provided?
Thank you!

**Comment by Javrd** [comment]
@paulhybryant Yes I did. As I explained in this thread, first I built the technosoft2000 docker-alpine-base changing in the dockerfile to the arm32v6 alpine version. Then I built this calibre dockerfile that changing the base for the image that I compiled first. Though, it was for arm**32**, not 64.

You can do it yourself cloning [this repository](https://github.com/Technosoft2000/docker-alpine-base) and changing the dockerfile to use [your desired architecture](https://hub.docker.com/r/arm64v8/alpine/). Then, you have to clone this repository and change the dockerfile to use your built image instead of the image from the dockerhub repository.

It should work, but remember that kindlegen doesn't support arm so you can't use this covert tool.

**Comment by paulhybryant** [comment]
Thanks @Javrd.

What your describe is what I did, but the process fails when it tries to install calibre.
The calibre installer will try to use the release distribution from the calibre project,
but the binary there is compiled for x86 cpu. Is the cpu architecture of your raspberry pi x86, not arm?

**Comment by Technosoft2000** [comment]
Providing an image with kindlegen as converter is not possible because Amazon has no ARM build of it,
and also the Calibre installer is only a x86 package available and compiling a own version is not that easy.

Linuxserver.io provides a docker image for

* ARM - https://hub.docker.com/r/lsioarmhf/calibre-web/
* ARM 64bit - https://hub.docker.com/r/lsioarmhf/calibre-web-aarch64/

which is without calibre and kindlegen.

**Comment by Technosoft2000** [comment]
> But I guess I just cannot do any format conversion there.

Correct this is not possible.

You're welcome @paulhybryant

**Comment by Technosoft2000** [comment]
Closed because I've no time to provide such images and Linuxserver.io has already working ones :)
