### ISSUE TITLE
"DB location is not valid, please enter correct path"

### ISSUE THREAD

**Issue by sekongqi** [Technosoft2000/docker-calibre-web#22]
I wrote '\books' in the 'Location of Calibre database', but it told me that "DB location is not valid, please enter correct path". Later I 'chmod 777 \books', but the same hint appeared. How to solve it?
P.S I use the same command to create and run calibre-web
'''
docker create --name=calibre-web --restart=always \
-v /volume1/books/calibre:/books \
-v /volume1/docker/apps/calibre-web/config:/calibre-web/config \
-e USE_CONFIG_DIR=true \
-e SET_CONTAINER_TIMEZONE=true \
-e CONTAINER_TIMEZONE=Europe/Vienna \
-e PGID=65539 -e PUID=1029 \
-p 8083:8083 \
technosoft2000/calibre-web
'''

**Comment by sekongqi** [comment]
Oh, it suddenly works! It's weird.

**Comment by Technosoft2000** [comment]
You wrote that you used _\books_ as path which contains a backslash which of course is not valid, be aware that you always us _/books_ with a slash :)

**Comment by gerroon** [comment]
For the future reference, try to chmod 777 metadata.db I just hit the similar issue until docker could access to this file
