### ISSUE TITLE
Kindlegen volume

### ISSUE THREAD

**Issue by bodybybuddha** [Technosoft2000/docker-calibre-web#24]
Can we have the details of the repo reflect that if you use the USE_CONFIG_DIR environment variable, you'll need to have the kindlegen binary in a subdirectory called kindlegen of where you've pointed the other config files (app.db & drive.db)?

Took me a little bit of time to figure this out - I ended up just creating a different directory for kindlegen , outside of the directories I used for app.db & gdrive.db.

Here are the relevant lines from my docker-compose:
    volumes:
      - /data/CalibreLib:/books
      - /data/cps:/calibre-web
      - /data/cps/config:/calibre-web/config
      - /data/cps/kindlegen:/calibre-web/kindlegen
    environment:
      - USE_CONFIG_DIR=true

**Comment by Technosoft2000** [comment]
Hi @bodybybuddha 

in my latest release v1.1.11 I've exposed now the additional directories and I've updated the README.md with the Container Directory Structure.

Here also the structure:

```
 /
   |- books
   |- calibre-web
       |- app
       |    |- "all Calibre Web Application files"
       |    |- app.db -> /calibre-web/config/app.db
       |    |- gdrive.db -> /calibre-web/config/gdrive.db
       |    |- calibre-web.log
       |    |- cps 
       |    |    |- *.py
       |    |    |- *.pyc
       |    |
       |    |- vendor
       |         |- kindlegen -> /calibre-web/kindlegen/kindlegen
       |
       |- config
       |    |- app.db
       |    |- gdrive.db
       |
       |- kindlegen
            |- EULA*.txt
            |- KindleGen Legal Notices*.txt
            |- docs
            |- kindlegen
            |- manual.html
```

**Comment by bodybybuddha** [comment]
Awesome! Thanks!!
