### ISSUE TITLE
using google drive

### ISSUE THREAD

**Issue by saitoh183** [Technosoft2000/docker-calibre-web#27]
Following the instructions on the calibre-web git.. step 8 it says to copy the json file to `calibre-web/cps` but this path only exist in the container. I cant make it persistent because it is only created when i start the docker container...So what do i do?

**Comment by Technosoft2000** [comment]
Please try my latest release v1.1.11 where you've the possibility to map _calibre-web/app_ and get access to  the cps directory at _calibre-web/app/cps_

At the README.md you'll find also the details - here an example how the volume mapping looks like:

```
docker create --name=calibre-web --restart=always \
-v /volume1/books/calibre:/books \
-v /volume1/docker/apps/calibre-web/app:/calibre-web/app \
-v /volume1/docker/apps/calibre-web/config:/calibre-web/config \
-v /volume1/docker/apps/calibre-web/kindlegen:/calibre-web/kindlegen \
-e PGID=65539 -e PUID=1029 \
-p 8083:8083 \
technosoft2000/calibre-web
```

**Comment by saitoh183** [comment]
@Technosoft2000 thank you. I was able to setup google drive. By any chance do you know what goes in the Calibre Base URL field if I use calibre via docker container (docker-rdp-calibre). I open it via guacamole using rdp so I'm not sure what to enter

**Comment by Technosoft2000** [comment]
@saitoh183 I'm sorry I've no idea what's there the correct setting.
Nevertheless you shouldn't use two different solutions at the same time on the same Calibre library, because it could damage your Calibre database file.

**Comment by saitoh183** [comment]
I figured it out. The thing is that using the Google drive setup in Calibre-web allows calibreweb to  auto sync your metadata.db to google drive when it gets modified. So it shouldn't get corrupted. But i get your point.
