### ISSUE TITLE
Upload button vanished

### ISSUE THREAD

**Issue by Wursthandschuh** [Technosoft2000/docker-calibre-web#31]
worked earlier, but it's not there anymore. Allow uploads is checked

**Comment by Wursthandschuh** [comment]
changing the upload settings on and off multiple times did the trick. weird

**Comment by Technosoft2000** [comment]
Hi @Wursthandschuh 

sorry for the late answer - I've checked the issue with the latest Calibre-Web update and no matter which theme I use I've always the upload button, so I've no idea how this can happen.
