### ISSUE TITLE
Dev Usage

### ISSUE THREAD

**Issue by bodybybuddha** [Technosoft2000/docker-calibre-web#39]
Hey @Technosoft2000 -  as you know I use your image in my docker environment.  However, I'm starting to use it for development purposes.  Having the image pull a configurable repo/branch is awesome!

Could you take it one step further?  Could you add an environment variable that will skip the check for the latest commits?  But continue to do everything else in the script?  For instance the symbolic links to the databases, etc.

Here is my workflow for developing:  

1. I create two docker containers, one based off your image, and another based on the calibre-rdp image.  I use docker-compose and fire up containers that share my books/database.  
2. Then, I go and delete the app directory (I mount this in the docker-compose) and recreate it with nothing in it.  
3. Then I go into my source control GUI (I use SourceTree) and I clone my target repo into the new app folder.
4. Then I restart the containers.  This will execute your code again, but a number of errors pop up regarding git commits, etc.

So far the script fails since the git data is not what it's expecting.  However, the script doesn't make any changes to my modified code or the git info - thus, everything works and I'm able to move forward with checking in my modifications into my local git and push to GitHub, etc.  I'm taking advantage of this "error" for my purposes. Although having the environment variable to bypass the check would give me some comfort that nothing is going to happen to my modified code.

Let me know what you think!

Thanks!

**Comment by Technosoft2000** [comment]
Hi @bodybybuddha,

you can set the environment variable **ADVANCED_DISABLEUPDATES** to _true_ to deactivate the update  function (`git pull`). Please try it and let me know if this is enough for your use-case :)

Here is the script which is executed in background: https://github.com/Technosoft2000/docker-alpine-base/blob/master/checkout.sh

**Comment by bodybybuddha** [comment]
NICE!  I didn't even think to look into the base image! I'll give it a go today.

**Comment by bodybybuddha** [comment]
WOOT!  Been using it the last couple of days and no problems!  Thanks!
