### ISSUE TITLE
 Can not start on my synology

### ISSUE THREAD

**Issue by fel835** [Technosoft2000/docker-calibre-web#45]
log like this
![f46915b2-0967-4c79-b112-7f773e1470aa](https://user-images.githubusercontent.com/2617716/50563475-101b0480-0d58-11e9-8955-383f080b5d6f.png)

**Comment by Technosoft2000** [comment]
Hi @fel835 

I don't see any issue in your screenshot - cloning the github repo takes a little bit of course.
So what is the issue? Does it stuck at this point?
Did you really used the correct User ID and Group ID (your owns and not that from the example) while container instance creation?
Which docker version are you running? Which Synology NAS do you use?

**Comment by fel835** [comment]
Yes,it stuck at this point,i used correct User ID and Group ID,the Synology NAS version is DS218+,i don't know why the process stucked.

**Comment by Technosoft2000** [comment]
Great to hear that it works now :)
