### ISSUE TITLE
which calibredb docker you preferred？

### ISSUE THREAD

**Issue by shenngw1127** [Technosoft2000/docker-calibre-web#47]
Hi, i have used this docker build my calibre web. But i want to auto import the meta data of books. Which calibredb docker is better?

https://hub.docker.com/r/thraxis/lazylibrarian-calibre 
https://hub.docker.com/r/jakbutler/docker-calibredb

Thanks!

sheng

**Comment by Iristyle** [comment]
lazylibrarian-calibre is regularly updated... docker-calibredb is 2 years old
