### ISSUE TITLE
remember page of a book

### ISSUE THREAD

**Issue by daviddoji** [Technosoft2000/docker-calibre-web#51]
Is there a way that calibre-web remember the page you left a book for a future reading?

Thanks in advance!

**Comment by Technosoft2000** [comment]
This works already is I can see - I've tested it with an epub with Google Chrome without any issue at all. It uses the browser local storage for this feature (check with F12 Developer Tools), so if you delete the browser cache (e.g. feature enabled by closing of the browser, manual cleanup, usage of incognito feature, usage of a cleaning tool like CCleaner, ...) then the "bookmark" of the page is lost.

If you've further questions regarding the application then please ask at https://github.com/janeczku/calibre-web/ where the application is actively developed.
