### ISSUE TITLE
pdf convert to epub failed

### ISSUE THREAD

**Issue by ariesdevil** [Technosoft2000/docker-calibre-web#52]
log is here:
```
::ffff:172.17.0.1 - - [2019-03-05 11:36:04] "GET /admin/book/1 HTTP/1.1" 200 22814 0.062351
::ffff:172.17.0.1 - - [2019-03-05 11:36:19] "POST /admin/book/convert/1 HTTP/1.1" 302 887 0.020823
::ffff:172.17.0.1 - - [2019-03-05 11:36:19] "GET /admin/book/1 HTTP/1.1" 200 23382 0.065116
[2019-03-05 11:36:19,440] INFO in worker: Book id 1 - target format of .epub does not exist. Moving forward with convert.
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/ebooks/conversion/cli.py", line 391, in main
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1106, in run
  File "site-packages/calibre/customize/conversion.py", line 244, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_input.py", line 52, in convert
  File "site-packages/calibre/ebooks/pdf/pdftohtml.py", line 89, in pdftohtml
ConversionError: pdftohtml failed with return code: -11
/opt/calibre/bin/pdftohtml: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/bin/pdftohtml)
[2019-03-05 11:36:20,319] INFO in worker: ebook converter failed with error while converting book
[2019-03-05 11:36:20,320] ERROR in worker: Ebook converter failed with unknown error
::ffff:172.17.0.1 - - [2019-03-05 11:38:58] "GET /stats HTTP/1.1" 200 12090 0.249705
```

**Comment by ariesdevil** [comment]
![image](https://user-images.githubusercontent.com/7812909/53803213-017ee280-3f7f-11e9-8cfc-a9fa6fc81b1f.png)

**Comment by Technosoft2000** [comment]
Hi @ariesdevil,

the issue happens at the Calibres ebook-convert tool. Did you also tried to convert the pdf via the original Calibre application, and does it work there?
Btw. could you please provide the pdf which causes the problem, otherwise it isn't possible to check why the problem happens.

**Comment by ariesdevil** [comment]
Converting can be perform successfully via original Calibre application. You can fetch the PDF from [Akka in action](https://www.jianguoyun.com/p/DbmvUVoQkq6aBhjgwqYB)

**Comment by Technosoft2000** [comment]
Hi @ariesdevil, 
I've tested your mentioned PDF and I can reproduce the issue, I try to build a new container with the actual calibre version to see if the issue happens there to.
There seems to be a function call mismatch with the current version inside the container:
```
/opt/calibre/bin/pdftohtml: Relink `/lib/libuuid.so.1' with `/usr/glibc-compat/lib/libc.so.6' for IFUNC symbol `strncpy'
```

**Comment by Technosoft2000** [comment]
I've tried it now with a newer version of **glibc 2.29-r0** from https://github.com/sgerrand/alpine-pkg-glibc and with the actual **ebook-convert (calibre 3.40.1)** and it still doesn't work .

So it's a mismatch problem between musl libc and glibc libraries and seems it is a known issue https://github.com/sgerrand/alpine-pkg-glibc/issues/97
The best solution would be to get Calibre compiled against musl libc but this isn't that simple :-/

I'll keep you updated if I've something new.

**Comment by Technosoft2000** [comment]
New docker image v1.3.3 is available which fixes this issue

**Comment by ariesdevil** [comment]
Thanks!
