### ISSUE TITLE
How to convert a book?

### ISSUE THREAD

**Issue by gerroon** [Technosoft2000/docker-calibre-web#53]
HI

I added ebook-convert to the settings. I see it is set in the about page. How do I convert a book from pdf to epub (as images for instance)? I do not see any convert etc type button anywhere i8ncluding in the book detail pages.

**Comment by Technosoft2000** [comment]
Hi @gerroon,

1. select an ebook
2. press the 'Edit metadata' button
3. on the left side you will see then two combo boxes where you can select 'Convert from' and 'Convert to' values and press the 'Convert ebook' button to convert it

See for screenshots at:
https://github.com/janeczku/calibre-web/wiki

If you've further questions regarding the application then please ask at https://github.com/janeczku/calibre-web/ where the application is actively developed.

**Comment by gerroon** [comment]
thanks
