### ISSUE TITLE
Unable to upload file greater than 30Mb

### ISSUE THREAD

**Issue by Sebastiaan76** [Technosoft2000/docker-calibre-web#54]
Hi there,
Is there a way to increase the allowed file size for uploading books? The file upload itself seems to work, but then I get an error 413 Request Entity Too Large<. I've tried editing /cps/reverseproxy.py to add a ```client_max_body_size   500M;``` directive, but it's not working. 

I have my own nginx reverse proxy sitting in front of the container to allow me to use a hostname to access Calibre web + add SSL ( which works fine ). I do have client_max_body_size set there too, it's not that nginx that is throwing the error.

Interestingly, if I try to upload the same file without using my nginx ( i.e. by accessing calibre web directly using http://<ip_address>:<port>/) I get an error as well, but without any description, it just says 'Error' after trying to convert the file for a while.

It's like the Upload itself works, but then it throws the error during conversion.

Either way, it would be handy to be able to specify this via an ENV in future.

Failing that, how can I get this working within the running container?

The logs also dont' seem to be showing me any useful information.

**Comment by Technosoft2000** [comment]
Hi @Sebastiaan76,

I'll do some tests and give you feedback as soon as possible.
I'm not sure if it is really an issue with the container or with the application itself, but I'll check it.

The application is actively developed at https://github.com/janeczku/calibre-web/ and I provide only the  docker container for it :)

**Comment by Technosoft2000** [comment]
Closed because it should be already supported by Calibre-Web - see also at latest issue https://github.com/janeczku/calibre-web/issues/1260
