### ISSUE TITLE
Not possible for symlinks to be created

### ISSUE THREAD

**Issue by seriouslyharmed** [Technosoft2000/docker-calibre-web#6]
When the check for permissions is run it doesn't always respond with 4 numbers for your permissions. This means that the logic that checks if you have permissions will always return 0 and so never create the symlink. An easy fix would be to change line 16 in get_or_update.sh to the following

`INFO=( $(stat -L -c "%0a %G %U" $DIR) )`

In order to add the missing zero. This of course isn't a good solution, you would be better off checking the number of symbols in PERM and making sure they add up to 4 instead.

**Comment by Technosoft2000** [comment]
@seriouslyharmed 
I'll fix the issue and check and test this in detail in the next days.
