### ISSUE TITLE
Metadata from Amazon

### ISSUE THREAD

**Issue by ngodfriedt** [Technosoft2000/docker-calibre-web#69]
When I'm trying to get metadata of a book, I'm getting only Google results. With a previous version I also got results from Amazon. Is this removed in later versions or is there something wrong with the docker? I do not see any error messages in the log.

Can you please let me know? Thanks

Regards, 

Niels

**Comment by OzzieIsaacs** [comment]
I think you mix something up, Amazon was requested, but never implemented. 
The chinese provider Douban was implemented in earlier releases. Due to a change in the api it stopped working. Douban is now integrated and working again.

**Comment by ngodfriedt** [comment]
O ok, but it is supported in Calibre. Is it possible to add it to the docker?

**Comment by OzzieIsaacs** [comment]
This was discussed in janeczku/calibre-web/issues#891 and janeczku/calibre-web#380. 
AS far as I remember the calibre implementation grabs the content from the amazon webpage and analyzes it.
(It is not a docker issue, it has to be implemented in calibre-web)

**Comment by Technosoft2000** [comment]
Calibre and Calibre-Web has different implementations to retrieve metadata from the target sites, so you can't easily integrate this functionality from the original Calibre desktop application into the docker container to get this work with Calibre-Web. A dedicated Amazon metadata scrapper has to be implemented for Calibre-Web, and once this is done it will work with the docker container too.

**Comment by ngodfriedt** [comment]
Ok, thanks for your answer!
