### ISSUE TITLE
I forgot my password

### ISSUE THREAD

**Issue by tanst** [Technosoft2000/docker-calibre-web#71]
Hello,
I forgot my password，How can I retrieve my password?
If I forgot my username?

**Comment by Technosoft2000** [comment]
Seams not possible yet - there is a feature request at Calibre Web Development page 
https://github.com/janeczku/calibre-web/issues/1063

**Comment by b0red** [comment]
If i'd like to edit the app.db, what format/encryption should I when generating a new password?

**Comment by OzzieIsaacs** [comment]
I implemented the password forget feature. 
After a new pull from the original repro it should work.

The password is generated with this method='pbkdf2:sha256'. The hash for the original password admin123 is: 

pbkdf2:sha256:150000$1JCgB2c1$aec258fa6cd4022dc07e0f5e4f5cf32b37a2322274135a738ecca0c8ff197b5e

**Comment by Technosoft2000** [comment]
The latest version of Calibre-Web has also now a **FORGOT PASSWORD** button :)
