### ISSUE TITLE
Add Flask_SimpleLDAP and Comic_API library support.

### ISSUE THREAD

**Issue by OrwillT** [Technosoft2000/docker-calibre-web#72]
Add Flask_SimpleLDAP and Comic_API library support.

**Comment by Technosoft2000** [comment]
Hi @OrwillT,
I'll check this in the next days

**Comment by Technosoft2000** [comment]
New docker image v1.3.3. is available where I've added the additional dependencies. The web UI shows that both libraries are not available, but while docker image creation I've seen in the log that it was successfully installed.

**Comment by ground7** [comment]
If you remove the hardcode to False as shown in [this commit](https://github.com/janeczku/calibre-web/commit/d82289e3039f1b2477545ea7d622848f6f7ec592) in both cps/admin.py and cps/web.py, then ldap works, although it's only partially implemented. I had to make users in calibre-web that matched the users in my ldap database, though they took on the ldap passwords in my database just fine.

**Comment by ground7** [comment]
I added a pull request to [janeczku/calibre-web](https://github.com/janeczku/calibre-web/pull/1120). If it gets added LDAP should be fully integrated and working with some halfway decent features.

**Comment by Technosoft2000** [comment]
Many thanks @ground7 for your support

**Comment by Technosoft2000** [comment]
Closed because it seems to work already :)
