### ISSUE TITLE
Synology Docker: failed to initialize logging driver: database is locked

### ISSUE THREAD

**Issue by destynate** [Technosoft2000/docker-calibre-web#73]
cheers :)

yesterday my calibre-web docker stopped and tries to restart it self 6 million times.
via portainer i was able to see whats going on here. seems like the database is locked? oO

here's the output from portainer:
State
Dead false
Error failed to initialize logging driver: database is locked
ExitCode 2
FinishedAt 2019-12-22T15:49:36.388605596Z
FinishedTs 1577029776
OOMKilled false
Paused false
Pid 0
Restarting false
Running false
StartedAt 2019-12-22T15:49:35.444195507Z
StartedTs 1577029775
Status exited

what should i do :O Calibre-web runs flawlessly for sever weeks not =(

**Comment by Technosoft2000** [comment]
Hi @destynate,

I'm sorry but I've no knowledge about portainer. The output seems something about portainer self and is no log output from the docker container.

The error message `Error failed to initialize logging driver: database is locked` comes from the docker engine and means that the docker engine/demon is not able to connect to your docker logging database.

For more information about docker log drivers look here:
https://docs.docker.com/config/containers/logging/configure/

**Comment by Technosoft2000** [comment]
Closed because I can't reproduce such issue and there was no additional reaction anymore.
