### ISSUE TITLE
Error after update (0.66) QNAP Docker

### ISSUE THREAD

**Issue by BerlinBased** [Technosoft2000/docker-calibre-web#78]
After updating calibre-web online, the calibre-web is no longer available from my Qnap Docker. 
 [INFO] Launching Calibre-Web ...                                                                                                               
Traceback (most recent call last):                                                                                                             
  File "/calibre-web/app/cps.py", line 39, in <module>                                                                                         
    from cps.about import about                                                                                                                
  File "/calibre-web/app/cps/about.py", line 52, in <module>                                                                                   
    Platform = '{0.system} {0.release} {0.version} {0.processor} {0.machine}'.format(platform.uname()),                                        
AttributeError: 'tuple' object has no attribute 'system'

**Comment by Technosoft2000** [comment]
I'm sorry but I've no idea what you mean, your description is totally unclear. I also have no QNAP NAS to test if there could be any issue.

**Comment by atomicbeecz** [comment]
Hi, i guess he means, that he updated to the latest docker version of calibre-web (1.4.1) and the app stopped to work. 

I run docker as well and have similar issue with latest docker version.
I can see in the docker log following:

[INFO] Change the ownership of /tmp (including subfolders) to calibre:calibre
[INFO] Launching Calibre-Web ...
Traceback (most recent call last):
  File "/calibre-web/app/cps.py", line 43, in <module>
    from cps.editbooks import editbook
  File "/calibre-web/app/cps/editbooks.py", line 456
    saved_filename, *os.path.splitext(requested_file.filename), config.config_rarfile_location)
SyntaxError: only named arguments may follow *expression

(i've even tried to remove the docker volume for the app)

my docker-compose.yml:
`version: '3.4'
services:
  calibre_web:
    restart: always
    image: technosoft2000/calibre-web:latest
    container_name: calibre-web
    hostname: calibre-web
    network_mode: "bridge"
    ports:
      - "8083:8083"

    environment:
      PUID: "1001" #same as the owner of books in calibre-web_books volume for example
      PGID: "1001"
      SET_CONTAINER_TIMEZONE: "true"
      TZ: "Europe/Prague"

    volumes:
      - "calibre-web_config:/config"
      - "calibre-web_config:/calibre-web/config"
      - "calibre-web_kindlegen:/calibre-web/kindlegen"
      - "calibre-web_app:/calibre-web/app"
      - "calibre-web_books:/books"

volumes:
  calibre-web_config:
    external: true
  calibre-web_kindlegen:
    external: true
  calibre-web_app:
          #    external: true
  calibre-web_books:
    external: true
`

**Comment by atomicbeecz** [comment]
ok, sorry, my issue is related to: https://github.com/janeczku/calibre-web/issues/1355

**Comment by Technosoft2000** [comment]
Thanks for that info - switched with v1.5.0 from **python2** to **python3** which runs correctly now.
