### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by happyhezun** [Technosoft2000/docker-calibre-web#79]
Database error: (sqlite3.OperationalError) attempt to write a readonly database [SQL: INSERT INTO authors (name, sort, link) VALUES (?, ?, ?)] [parameters: (u'Unknown', u'Unknown', u'')] (Background on this error at: http://sqlalche.me/e/e3q8).

**Comment by happyhezun** [comment]
[WARNING] No write access at /books - new 'metadata.db' and books can't be stored at this directory
> Please check and modify the permissions of the directory

bash-4.4# chown calibre.calibre /books -R

**Comment by Technosoft2000** [comment]
With these information it's not possible to reproduce the issue what you've. Give more context and write details how you created the docker container and post the full log of the container startup.

**Comment by Technosoft2000** [comment]
Didn't got any additional info and therefore the issue gets closed!
