### ISSUE TITLE
I can't read my e-books in Calibre-Web.

### ISSUE THREAD

**Issue by Yngda** [Technosoft2000/docker-calibre-web#81]
I can't find the "raed" button in management panel. E-books can't be read online, but they could be downloaded.
And I found an issue like mine: https://github.com/Technosoft2000/docker-calibre-web/issues/65 , but it can't work my problem out.

Calibre-Web version: 0.6.8;
OS: Debain 9.6;
Browser: Google Chrome, version 83.0.4103.97.

**Comment by damianperera** [comment]
I have this same issue, and I can't see the checkbox to grant 'reader' permissions for the admin user.
![Screenshot_20210217_073204](https://user-images.githubusercontent.com/15967502/108145942-452e7080-70f2-11eb-81ec-3aa48b64a7c9.png)
