### ISSUE TITLE
Converter buttons not displaying on Epubs

### ISSUE THREAD

**Issue by timmehtimtims** [Technosoft2000/docker-calibre-web#86]
Epub books do not have the option to convert to mobi and send to kindle.
I have added `/opt/calibre/ebook-convert` as the path to the converter took in `basic config settings > external binaries > Path to Calibre E-Book Converter`.
I can't find reference to any other settings but I may be missing something.

Under 'About' it states `ebook-convert (calibre 4.13.0)`.

Can anyone help?

**Comment by odinis** [comment]
Same issue here too. The button is not present despite the Send to Kindle email is in place and MOBI file was generated.

**Comment by Technosoft2000** [comment]
Tested with Calibre-Web v0.6.8

1. Select an ebook
2. press the Edit Metadata button
3. you'll get the possibility to convert books via **Convert from** and **Convert to** combo box

Here the screenshot:
<img width="1109" alt="Convert" src="https://user-images.githubusercontent.com/1690853/92997881-d9c6ee00-f516-11ea-8a95-fb22b61842ad.png">
