### ISSUE TITLE
Build failure in v1.4.1

### ISSUE THREAD

**Issue by greenaar** [Technosoft2000/docker-calibre-web#87]
Connecting to www.archlinux.org (138.201.81.199:443)
wget: server returned error: HTTP/1.1 404 Not Found
The command '/bin/sh -c wget "https://www.archlinux.org/packages/core/x86_64/libutil-linux/download/" -O /tmp/libutil-linux.tar.zst     && mkdir -p /tmp/libutil-linux     && tar -xf /tmp/libutil-linux.tar.zst -C /tmp/libutil-linux     && cp -rP /tmp/libutil-linux/usr/lib/* /usr/glibc-compat/lib     && /usr/glibc-compat/sbin/ldconfig     && rm -rf /tmp/libutil-linux /tmp/libutil-linux.tar.zst' returned a non-zero code: 1

This package does not exist at the location specified, it looks like they've renamed it. As such, a docker build fails.

**Comment by Technosoft2000** [comment]
Hi @greenaar 

thanks for the hint - I'll try to fix it in the next days and I've also to update the image to a newer Alpine Version.
The new URL is https://www.archlinux.org/packages/core/x86_64/util-linux-libs/download with the file `util-linux-libs-2.36-4-x86_64.pkg.tar.zst` which replaces the old `libutil-linux` package.

**Comment by Technosoft2000** [comment]
Planned to be fixed with v1.5.0 and updated for this upcoming release the Alpine-Base image to Alpine 3.12.0 https://github.com/Technosoft2000/docker-alpine-base/releases/tag/3.12-1

**Comment by Technosoft2000** [comment]
Fixed it with v1.5.0 - thanks for the patience.
