### ISSUE TITLE
[BUG] In version 1.1.4 /books folder doesn't have write access

### ISSUE THREAD

**Issue by Kyosfonica** [Technosoft2000/docker-calibre-web#9]
I am using a Synology DSM 6.0.2 and I have set the PUID and GUID to a docker user I've created. It owns the volume where /books is stored.

In version 1.1.3 it works perfect but when I update the container to use version 1.1.4 it fails detecting the folder permissions and I lose all my configuration and settings because refuses to use /books as the save path for the *.db files.

V. 1.1.3 LOG:
[INFO] Everyone has write access at /books
[INFO] app.db and gdrive.db will be linked into /books
[INFO] Launching Calibre-Web ...

V. 1.1.4 LOG:
[INFO] Checking permissions of /books
&gt; Output is: 755 users UNKNOWN
&gt; Permissions: 755
&gt; Assigned group: users
&gt; Assigned owner: UNKNOWN
&gt; Using permissons for checks: 0755
[WARNING] No write access at /books - app.db and gdrive.db wont be linked into /books
[INFO] Creating directory for temporary directories and files: /tmp
[INFO] Change the ownership of /tmp (including subfolders) to calibre:calibre
[INFO] Launching Calibre-Web ...

**Comment by Technosoft2000** [comment]
Hi,

could you please also provide information of

`$ id <dockeruser>`

and

`$ docker inspect calibre-web`

and the whole log of v1.1.4.

The assigned group of _/books_ should be **calibre** inside the docker container and not **users**, which would be the case when PUID and GUID is correctly assigned to the internal group **calibre** and user **calibre**.
So I need the above mentioned information to clarify where and why the issue happens, thanks.

**Comment by Technosoft2000** [comment]
I've recreated the container now on my Synology with DSM 6.1.3-15152 Update 1 

my docker user id:
```
# id docker
uid=1029(docker) gid=100(users) groups=100(users),65539(docker)
```

my host rights for _/volume1/books/calibre_  (username removed now with placeholder _abcd_)
```
drwxrwx---  41 abcd users 4096 Jul 23 15:13 calibre
```

my docker command:
```
    docker create --name=calibre-web --restart=always \
    -v /volume1/books/calibre:/books \
    -e SET_CONTAINER_TIMEZONE=true \
    -e CONTAINER_TIMEZONE=Europe/Vienna \
    -e PGID=100 -e PUID=1029 \
    -p 8082:8083 \
    technosoft/calibre-web:v1.1.4
```

and get the following output:
```
[INFO] Docker image version: 1.1.4
[INFO] Alpine Linux version: 3.6.0
[WARNING] A group with id 100 exists already [in use by users] and will be modified.
[WARNING] The group users will be renamed to calibre
[INFO] Create user calibre with id 1029
[INFO] Current active timezone is UTC
Tue Jul 25 21:14:29 CEST 2017
[INFO] Container timezone is changed to: Europe/Vienna
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre
[INFO] Current git version is:
git version 2.13.0
[INFO] Checkout the latest Calibre-Web version ...
[INFO] ... git clone -b master --single-branch https://github.com/janeczku/calibre-web.git /calibre-web/app -v
Cloning into '/calibre-web/app'...
POST git-upload-pack (189 bytes)
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...
[INFO] ... current git status is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
a95e6aab6bdcc634f77167e2d315f0ca04f4f1d7
[INFO] ... pulling sources
Already up-to-date.
[INFO] ... git status after update is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
a95e6aab6bdcc634f77167e2d315f0ca04f4f1d7
[INFO] Checking permissions of /books
> Output is: 770 calibre UNKNOWN
> Permissions: 770
> Assigned group: calibre
> Assigned owner: UNKNOWN
> Using permissons for checks: 0770
> Check if the group calibre has write access at /books
> The group calibre has write access at /books
[INFO] app.db and gdrive.db will be linked into /books
[INFO] Creating directory for temporary directories and files: /tmp
[INFO] Change the ownership of /tmp (including subfolders) to calibre:calibre
[INFO] Launching Calibre-Web ...
```

So it works as expected now.

> I lose all my configuration and settings because refuses to use /books as the save path for the *.db files.

Your *.db files should be in your books directory on your host if they where really successfully created, they don't get lost after deletion of the container.

**Comment by Technosoft2000** [comment]
ok I see now that in your case only the user itself has write access and my check if the user is the owner doesn't work correct because the name doesn't exist inside the container and the output shows in your and my case that the owner name is UNKNOWN.

So I've to enhance the check to proof also if the User ID and Owner ID is the same.

Will try to fix this in the next days.

**Comment by Kyosfonica** [comment]
For lose my configuration I meant that with version 1.1.4 I do not have access to it. I haven't lose any information.

Sorry for the misunderstunding.

What I have here:

NAS:
```
# id docker
uid=1031(docker) gid=100(users) groups=100(users)
```

The docker container is built with GUID=100 and PUID=1031

The folder permissions are:
`4 drwxrwx---  70 abcd users 4096 Jul 25 11:12 calibre`

Docker logs:
```
[INFO] Docker image version: 1.1.4
[INFO] Alpine Linux version: 3.6.0
[INFO] Create group calibre with id 15000
[INFO] Create user calibre with id 1031
[INFO] Current active timezone is UTC
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre
[INFO] Current git version is:
git version 2.13.0
[INFO] Checkout the latest Calibre-Web version ...
[INFO] ... git clone -b master --single-branch https://github.com/Kyosfonica/calibre-web.git /calibre-web/app -v
Cloning into '/calibre-web/app'...
POST git-upload-pack (177 bytes)
remote: Counting objects: 6433, done.[K
remote: Compressing objects: 100% (63/63), done.[K
remote: Total 6433 (delta 62), reused 82 (delta 40), pack-reused 6323[K
Receiving objects: 100% (6433/6433), 30.18 MiB | 6.79 MiB/s, done.
Resolving deltas: 100% (3345/3345), done.
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...
[INFO] ... current git status is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
0185032fb21a6769fd5dc0ceb2be59f35319184c
[INFO] ... pulling sources
Already up-to-date.
[INFO] ... git status after update is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
0185032fb21a6769fd5dc0ceb2be59f35319184c
[INFO] Checking permissions of /books
&gt; Output is: 770 users UNKNOWN
&gt; Permissions: 770
&gt; Assigned group: users
&gt; Assigned owner: UNKNOWN
&gt; Using permissons for checks: 0775
&gt; Check if the group calibre has write access at /books
&gt; Check if the group : has write access at /books
&gt; Check if the group calibre has write access at /books
[WARNING] No write access at /books - app.db and gdrive.db wont be linked into /books
[INFO] Creating directory for temporary directories and files: /tmp
```

So even when the folder has -rwx permissions for both owner and group, the script fails in the detection. The user than executes the get_or_update.sh file is root or calibre?

**Comment by Technosoft2000** [comment]
At your log I see that your container doesn't have the GUID/GID which you say that you've defined
```
[INFO] Create group calibre with id 15000
[INFO] Create user calibre with id 1031
```
so it uses as GID the default value 15000 (and not your needed GID 100) 
but the UID is your correct value 1031.
Due the wrong GID the check of the permission for group fails (the check for user has to be corrected as mention in my previous answer)

Check your docker create command that you specify the right environment variables, in your case it should be:
```
-e PGID=100 -e PUID=1031
```
I think you've done a typo and entered e.g _-e GID=100_ or _-e GUID=100_ instead of _-e PGID=100_
You can check your container environment settings via:
```
docker inspect calibre-web
```

and once is specified correct you get the log:
```
[WARNING] A group with id 100 exists already [in use by users] and will be modified.
[WARNING] The group users will be renamed to calibre
[INFO] Create user calibre with id 1031
```

and then the creation of the symlink should work too, like it worked in my case.

**Comment by Kyosfonica** [comment]
My fault. I had a typo in the environment variable U^_^
Now it works fine although the user detection needs a fix.

Thanks for noticing.

**Comment by Technosoft2000** [comment]
Fixed it now - for testing I've used

```
docker create --name=calibre-web-test --restart=always \
-v /volume1/books/calibre-test:/books \
-e SET_CONTAINER_TIMEZONE=true \
-e CONTAINER_TIMEZONE=Europe/Vienna \
-e PGID=100 -e PUID=1026 \
-p 8090:8083 \
technosoft2000/calibre-web:v1.1.5
```

and the user 'abcd'
```
# id abcd
uid=1026(abcd) gid=100(users) groups=100(users),101(administrators)
```

and my books directory _/volume1/books/calibre-test_ has the following permissons 755
```
drwxr-xr-x   2 abcd users 4096 Jul 29 11:31 calibre-test
```

and got the following log
```
[INFO] Docker image version: 1.1.5
[INFO] Alpine Linux version: 3.6.0
[WARNING] A group with id 100 exists already [in use by users] and will be modified.
[WARNING] The group users will be renamed to calibre
[INFO] Create user calibre with id 1026
[INFO] Current active timezone is UTC
Sat Jul 29 11:50:15 CEST 2017
[INFO] Container timezone is changed to: Europe/Vienna
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre
[INFO] Current git version is:
git version 2.13.0
[INFO] Checkout the latest Calibre-Web version ...
[INFO] ... git clone -b master --single-branch https://github.com/janeczku/calibre-web.git /calibre-web/app -v
Cloning into '/calibre-web/app'...
POST git-upload-pack (189 bytes)
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...
[INFO] ... current git status is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
0afc8f94da4f89f57a7dd098d97c2f4f83a0d723
[INFO] ... pulling sources
Already up-to-date.
[INFO] ... git status after update is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
0afc8f94da4f89f57a7dd098d97c2f4f83a0d723
[INFO] kindlegen (Amazon Kindle Generator) will be linked into /calibre-web/app/vendor
> create kindlegen link /calibre-web/app/vendor/kindlegen assigned to source /calibre-web/kindlegen/kindlegen
[INFO] Checking permissions of /books
> Output is: 755 calibre 100 calibre 1026
> Permissions: 755
> Assigned group: calibre
> Assigned group ID: 100
> Assigned owner: calibre
> Assigned owner ID: 1026
> Using permissions for checks: 0755
> The user calibre:1026 is the owner and has write access at /books
[INFO] app.db and gdrive.db will be linked into /books
> create app.db link /calibre-web/app/app.db assigned to source /books/app.db
> create gdrive.db link /calibre-web/app/gdrive.db assigned to source /books/gdrive.db
[INFO] Creating directory for temporary directories and files: /tmp
[INFO] Change the ownership of /tmp (including subfolders) to calibre:calibre
[INFO] Launching Calibre-Web ...
```

**Comment by Kyosfonica** [comment]
With version 1.1.6

[INFO] Checking permissions of /books
&gt; Output is: 777 calibre 100 UNKNOWN 1029
&gt; Permissions: 777
&gt; Assigned group: calibre
&gt; Assigned group ID: 100
&gt; Assigned owner: UNKNOWN
&gt; Assigned owner ID: 1029
&gt; Using permissions for checks: 0777
&gt; Everyone has write access at /books
[INFO] app.db and gdrive.db will be linked into /books
&gt; create app.db link /calibre-web/app/app.db assigned to source /books/app.db
&gt; create gdrive.db link /calibre-web/app/gdrive.db assigned to source /books/gdrive.db
[INFO] Creating directory for temporary directories and files: /tmp
[INFO] Change the ownership of /tmp (including subfolders) to calibre:calibre
[INFO] Launching Calibre-Web ...

**Comment by lappat** [comment]
Hi,

i have a permission, but not sure how to fix it.

i have this odcker install on my synologyDS718+

i have the following error:

[WARNING] No write access at /books - app.db and gdrive.db wont be linked into /books
[INFO] Checking permissions of the books directory: /books
Output is: 660 UNKNOWN 911 UNKNOWN 911
Permissions: 660
Assigned   group: UNKNOWN--
Assigned   group ID: 911
Assigned   owner: UNKNOWN
Assigned   owner ID: 911
Using permissions for checks: 0660
Check if the group calibre has write access at /books
The group calibre has no write access at /books
Check if the group : has write access at /books
The group : has no write access at /books
Check if the group calibre has write access at /books
The group calibre has no write access at /books
[WARNING] No write access at /books - new 'metadata.db' and books can't be stored at this directory
Please check and modify the permissions of the directory

what i need to do? i,m not so good with this.

regards
